name: download_ricevute_portale_alloggiati
description: A simple app to download receipts of Portale Alloggiati

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  datetime_picker_formfield: ^2.0.0
  file_picker: ^4.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  provider: ^6.0.2
  xml: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
